var fakeProducts = [
    {id: 1, category: 'Fiction', title: 'Fiction Title1', price: '111', description: 'Bla bla.'},
    {id: 2, category: 'Fiction', title: 'Fiction Title2', price: '112', description: 'Bla bla.'},
    {id: 3, category: 'Science', title: 'Science Title3', price: '113', description: 'Bla bla.'},
    {id: 4, category: 'Science', title: 'Science Title4', price: '114', description: 'Bla bla.'},
    {id: 5, category: 'Politics', title: 'Politics Title5', price: '115', description: 'Bla bla.'},
    {id: 6, category: 'Politics', title: 'Politics Title6', price: '116', description: 'Bla bla.'},

    {id: 7, category: 'Fiction', title: 'Fiction Title7', price: '111', description: 'Bla bla.'},
    {id: 8, category: 'Fiction', title: 'Fiction Title8', price: '112', description: 'Bla bla.'},
    {id: 9, category: 'Science', title: 'Science Title9', price: '113', description: 'Bla bla.'},
    {id: 10, category: 'Science', title: 'Science Title10', price: '114', description: 'Bla bla.'},
    {id: 11, category: 'Politics', title: 'Politics Title11', price: '115', description: 'Bla bla.'},
    {id: 12, category: 'Politics', title: 'Politics Title12', price: '116', description: 'Bla bla.'},
    
    {id: 13, category: 'Fiction', title: 'Fiction Title13', price: '111', description: 'Bla bla.'},
    {id: 14, category: 'Fiction', title: 'Fiction Title14', price: '112', description: 'Bla bla.'},
    {id: 15, category: 'Science', title: 'Science Title15', price: '113', description: 'Bla bla.'},
    {id: 16, category: 'Science', title: 'Science Title16', price: '114', description: 'Bla bla.'},
    {id: 17, category: 'Politics', title: 'Politics Title17', price: '115', description: 'Bla bla.'},
    {id: 18, category: 'Politics', title: 'Politics Title18', price: '116', description: 'Bla bla.'},
    
    {id: 19, category: 'Fiction', title: 'Fiction Title19', price: '111', description: 'Bla bla.'},
    {id: 20, category: 'Fiction', title: 'Fiction Title20', price: '112', description: 'Bla bla.'},
    {id: 21, category: 'Science', title: 'Science Title21', price: '113', description: 'Bla bla.'},
    {id: 22, category: 'Science', title: 'Science Title22', price: '114', description: 'Bla bla.'},
    {id: 23, category: 'Politics', title: 'Politics Title23', price: '115', description: 'Bla bla.'},
    {id: 24, category: 'Politics', title: 'Politics Title24', price: '116', description: 'Bla bla.'},
    
    {id: 25, category: 'Fiction', title: 'Fiction Title25', price: '111', description: 'Bla bla.'},
    {id: 26, category: 'Fiction', title: 'Fiction Title26', price: '112', description: 'Bla bla.'},
    {id: 27, category: 'Science', title: 'Science Title27', price: '113', description: 'Bla bla.'},
    {id: 28, category: 'Science', title: 'Science Title28', price: '114', description: 'Bla bla.'},
    {id: 29, category: 'Politics', title: 'Politics Title29', price: '115', description: 'Bla bla.'},
    {id: 30, category: 'Politics', title: 'Politics Title30', price: '116', description: 'Bla bla.'},
    
    
    {id: 31, category: 'Fiction', title: 'Fiction Title1', price: '111', description: 'Bla bla.'},
    {id: 32, category: 'Fiction', title: 'Fiction Title2', price: '112', description: 'Bla bla.'},
    {id: 33, category: 'Science', title: 'Science Title3', price: '113', description: 'Bla bla.'},
    {id: 34, category: 'Science', title: 'Science Title4', price: '114', description: 'Bla bla.'},
    {id: 35, category: 'Politics', title: 'Politics Title5', price: '115', description: 'Bla bla.'},
    {id: 36, category: 'Politics', title: 'Politics Title6', price: '116', description: 'Bla bla.'},
    
    {id: 37, category: 'Fiction', title: 'Fiction Title7', price: '111', description: 'Bla bla.'},
    {id: 38, category: 'Fiction', title: 'Fiction Title8', price: '112', description: 'Bla bla.'},
    {id: 39, category: 'Science', title: 'Science Title9', price: '113', description: 'Bla bla.'},
    {id: 40, category: 'Science', title: 'Science Title10', price: '114', description: 'Bla bla.'},
    {id: 41, category: 'Politics', title: 'Politics Title11', price: '115', description: 'Bla bla.'},
    {id: 42, category: 'Politics', title: 'Politics Title12', price: '116', description: 'Bla bla.'},
    
    {id: 43, category: 'Fiction', title: 'Fiction Title13', price: '111', description: 'Bla bla.'},
    {id: 44, category: 'Fiction', title: 'Fiction Title14', price: '112', description: 'Bla bla.'},
    {id: 45, category: 'Science', title: 'Science Title15', price: '113', description: 'Bla bla.'},
    {id: 46, category: 'Science', title: 'Science Title16', price: '114', description: 'Bla bla.'},
    {id: 47, category: 'Politics', title: 'Politics Title17', price: '115', description: 'Bla bla.'},
    {id: 48, category: 'Politics', title: 'Politics Title18', price: '116', description: 'Bla bla.'},
    
    {id: 49, category: 'Fiction', title: 'Fiction Title19', price: '111', description: 'Bla bla.'},
    {id: 50, category: 'Fiction', title: 'Fiction Title20', price: '112', description: 'Bla bla.'},
    {id: 51, category: 'Science', title: 'Science Title21', price: '113', description: 'Bla bla.'},
    {id: 52, category: 'Science', title: 'Science Title22', price: '114', description: 'Bla bla.'},
    {id: 53, category: 'Politics', title: 'Politics Title23', price: '115', description: 'Bla bla.'},
    {id: 54, category: 'Politics', title: 'Politics Title24', price: '116', description: 'Bla bla.'},
    
    {id: 55, category: 'Fiction', title: 'Fiction Title25', price: '111', description: 'Bla bla.'},
    {id: 56, category: 'Fiction', title: 'Fiction Title26', price: '112', description: 'Bla bla.'},
    {id: 57, category: 'Science', title: 'Science Title27', price: '113', description: 'Bla bla.'},
    {id: 58, category: 'Science', title: 'Science Title28', price: '114', description: 'Bla bla.'},
    {id: 59, category: 'Politics', title: 'Politics Title29', price: '115', description: 'Bla bla.'},
    {id: 60, category: 'Politics', title: 'Politics Title30', price: '116', description: 'Bla bla.'},
];